### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by JamesZlosnik** [USDA-VS/GenoFLU#1]
Hi,

This is an amazing tool, thank you!!  

We've just been trying it out for our data at it is working really well.  In order for us to better operationalize it would be helpful if it is possible to issue new versions as a release, rather than just a branch.  Just wanting to suggest this.

Thank you for considering!!

**Comment by stuber** [comment]
I’m glad to hear that it’s working well.

As of May 2024, the current version is 1.03. Using the -v or --version option will display the current version being used. When a new version is provided on GitHub, the conda package is updated. There is a corresponding 1.03 version in conda.

I have just added a “Release” to the GitHub page, which will help make the version more explicit at this repository.

Thanks for the suggestion.
