### ISSUE TITLE
GenoFLU Installation

### ISSUE THREAD

**Issue by mwylerCH** [USDA-VS/GenoFLU#2]
Dear Dev Team,
I wanted to try out your tool, however I struggle to run it. Already the test is delivering me the following error message:
```
genoflu.py set arguements:

        FASTA:  test-genome-A1.fasta
        FASTA_dir:  None
        cross_reference:  None
        sample_name:  CUCU
        debug:  True


cat: write error: Broken pipe
Traceback (most recent call last):
  File "/storage/homefs/mw23o336/.conda/envs/famsa/bin/genoflu.py", line 347, in <module>
    genoflu.blast_hpai_genomes()
  File "/storage/homefs/mw23o336/.conda/envs/famsa/bin/genoflu.py", line 177, in blast_hpai_genomes
    blast_hpai_genotyping = Blast_Fasta(FASTA=self.FASTA_abs_path, format="6 qseqid qseq length nident pident mismatch evalue bitscore sacc stitle", num_alignment=1, blast_db='hpai_geno_db', num_threads=2)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/homefs/mw23o336/.conda/envs/famsa/bin/genoflu.py", line 63, in __init__
    with open(blastout_file, 'r') as blast_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test-genome-A1_blast_out.txt'

```
I installed v1.03 using conda as described and furthermore I installed biopython using pip separately.

Overall, please correct me if I'm wrong, but the idea of GenoFLU is not to have a publicly available software but only for USDA internal use, I'm right?
Greetings

**Comment by stuber** [comment]
Hi, GenoFLU is available to the public. You should be able to use it.

I'm not sure what is causing the error.  With the "cat: write error:" I'm wondering if it could be a permissions issue at the location the file is being ran.  I just downloaded and ran GenoFLU to try and replicate the issue but could not get the error to replicate.  If it has not been tried already, I recommend changing to a directory under your home directory, copying the test-genome-A1.fasta to this directory and running genoflu from this directory, `genoflu.py -f test-genome-A1.fasta`.

**Comment by stuber** [comment]
Thank you for the feedback.  Instructions updated to use `conda create` instead of `conda install`.
