### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by DOH-PNT0303** [USDA-VS/GenoFLU#8]
Hi! I was wondering if you all had a reference to a paper for GenoFlu and how it works? Thank you! 

Pauline

**Comment by stuber** [comment]
Hi,  paper reference to GeneFlu is [here](https://www.sciencedirect.com/science/article/pii/S0042682223001733)

**Comment by DOH-PNT0303** [comment]
Thank you!! appreciate it :)
